/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tradingjournal;


import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;


import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;



public class signup1 extends javax.swing.JFrame {


    /**
     * Creates new form login
     */
    public signup1() {
        initComponents();
        this.icon2.setVisible(false);
        this.icon4.setVisible(false);
        pan_ed1.setBackground(new Color(0,0,0,80));
      
    }

    public void insertsignupdetails(){
        String username = tuser.getText();
        String password = tpassword.getText();
        String confirm_password = tconpassword.getText();
        String mobile = tmobile.getText();
        String email = temail.getText();
   
    if(tuser.getText().length()==0){
        JOptionPane.showMessageDialog(this,"Please enter username");
    }
    else if(tpassword.getText().length()==0){
        JOptionPane.showMessageDialog(this,"Please enter password");
    }
    else if(tpassword.getText().length()<=7){
        JOptionPane.showMessageDialog(this,"Password must have minimum of 8 character");
    }
    else if(tpassword.getText().equals(tconpassword.getText())==false){
        JOptionPane.showMessageDialog(this,"Password not matched");
    }
    else if(tmobile.getText().length()==0){
        JOptionPane.showMessageDialog(this,"Please enter mobile number");
    }
    else if(temail.getText().length()==0){
        JOptionPane.showMessageDialog(this,"Please enter email ID");
    }
    else if(temail.getText().matches("^.+@.+\\..+$")==false){
        JOptionPane.showMessageDialog(this,"Please enter valid email");
    }
    else{
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("insert into signup(username,password,confirm_password,mobile,email)values(?,?,?,?,?)");
        
            pst.setString(1,username);
            pst.setString(2,password);
            pst.setString(3,confirm_password);
            pst.setString(4,mobile);
            pst.setString(5,email);
       
            int updatedRowCount = pst.executeUpdate();
       
             if(updatedRowCount > 0){
                JOptionPane.showMessageDialog(this,"Account Created Successfully");
                login login = new login();
                login.setVisible(true);
                this.dispose();
            }
            else{
           JOptionPane.showMessageDialog(this,"Account Creation Failed");
            }

       
        }catch (Exception e){
            System.out.println(e);
        }
    }       
    }
    
    public boolean checkduplicateuser(){
        String username = tuser.getText();
        boolean isexist = false;
        
        try{
        Connection con = DBConnection.getConnection();
        PreparedStatement pst = con.prepareStatement("select * from signup where username = ?");
        
        pst.setString(1,username);
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()){
            isexist = true;
        }
        else{
            isexist = false;
        }
        
        }catch (Exception e){
            System.out.println(e);
        }
    return isexist;
}
     
 /*   public static boolean digitinpassword(String password){
   
    if(password.length()>7){
    if(charinpassword(password)){
    return true;
    }
    else{
    return false;
    }
    }
    else{
        System.out.println("password must have minimum of 8 character");
        return false;
    
    }
    }
    
    public static boolean charinpassword(String password){
    
    boolean hasnum = false;boolean hascap = false;boolean hassmall = false;char c;
    for(int i = 0;i < password.length();i++){
    c = password.charAt(i);
    if(Character.isDigit(c)){
    hasnum = true;
    }
    else if(Character.isUpperCase(c)){
    hascap = true;
    }
    else if(Character.isLowerCase(c)){
    hassmall = true;
    }
    if(hasnum && hascap && hassmall){
    return true;
    }
    }  
    return false;
    }
    
  */  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pan_ed1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        temail = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        tmobile = new app.bolivia.swing.JCTextField();
        tconpassword = new javax.swing.JPasswordField();
        tpassword = new javax.swing.JPasswordField();
        tuser = new app.bolivia.swing.JCTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        icon4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        rSMaterialButtonCircle1.setText("rSMaterialButtonCircle1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setText("jLabel5");

        jLabel1.setText("jLabel1");

        jRadioButton1.setText("jRadioButton1");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(810, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(810, 430));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 3, -1, 424));

        pan_ed1.setBackground(new java.awt.Color(0, 0, 0));
        pan_ed1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("TRADING");
        jButton1.setBorder(null);

        jButton3.setBackground(new java.awt.Color(0, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton3.setText("JOURNAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        pan_ed1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 9, 210, 40));

        jLabel12.setBackground(new java.awt.Color(0, 0, 102));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Already have an account !");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        pan_ed1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 600, 160, 20));

        jLabel11.setBackground(new java.awt.Color(0, 0, 102));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email ID ");
        pan_ed1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 170, 35));

        temail.setBackground(new java.awt.Color(0, 0, 0));
        temail.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        temail.setForeground(new java.awt.Color(255, 255, 255));
        temail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        temail.setPlaceholder("Enter Email ID");
        pan_ed1.add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 420, 210, 40));

        jLabel10.setBackground(new java.awt.Color(0, 0, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Username");
        pan_ed1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 170, 40));

        tmobile.setBackground(new java.awt.Color(0, 0, 0));
        tmobile.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        tmobile.setForeground(new java.awt.Color(255, 255, 255));
        tmobile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tmobile.setPlaceholder("Enter Mobile No.");
        tmobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmobileMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tmobileMousePressed(evt);
            }
        });
        tmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmobileActionPerformed(evt);
            }
        });
        tmobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tmobileKeyPressed(evt);
            }
        });
        pan_ed1.add(tmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 346, 210, 40));

        tconpassword.setBackground(new java.awt.Color(0, 0, 0));
        tconpassword.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tconpassword.setForeground(new java.awt.Color(255, 255, 255));
        tconpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        tconpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        tconpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tconpasswordActionPerformed(evt);
            }
        });
        pan_ed1.add(tconpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 274, 210, 40));

        tpassword.setBackground(new java.awt.Color(0, 0, 0));
        tpassword.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tpassword.setForeground(new java.awt.Color(255, 255, 255));
        tpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        tpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        tpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpasswordMouseClicked(evt);
            }
        });
        tpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpasswordActionPerformed(evt);
            }
        });
        pan_ed1.add(tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 194, 210, 40));

        tuser.setBackground(new java.awt.Color(0, 0, 0));
        tuser.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        tuser.setForeground(new java.awt.Color(255, 255, 255));
        tuser.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tuser.setPhColor(new java.awt.Color(255, 255, 255));
        tuser.setPlaceholder("Enter username");
        tuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tuserFocusLost(evt);
            }
        });
        tuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuserActionPerformed(evt);
            }
        });
        pan_ed1.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(997, 122, 210, 40));

        jLabel4.setBackground(new java.awt.Color(0, 0, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Create Account");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pan_ed1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 270, 50));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        pan_ed1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 37, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 102));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password");
        pan_ed1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 170, 40));

        jLabel14.setBackground(new java.awt.Color(0, 0, 102));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Confirm Password");
        pan_ed1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 210, 40));

        jLabel15.setBackground(new java.awt.Color(0, 0, 102));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mobile No. ");
        pan_ed1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 170, 40));

        jButton2.setBackground(new java.awt.Color(226, 30, 56));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SIGN UP");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pan_ed1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 510, 180, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\princy\\Desktop\\Brighton\\pic2\\user (2).png")); // NOI18N
        pan_ed1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 40, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\princy\\Desktop\\Brighton\\pic2\\password.png")); // NOI18N
        pan_ed1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 40, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\princy\\Desktop\\Brighton\\pic2\\password.png")); // NOI18N
        pan_ed1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 40, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\princy\\Desktop\\Brighton\\pic2\\email.png")); // NOI18N
        pan_ed1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 40, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\princy\\Desktop\\Brighton\\pic2\\telephone.png")); // NOI18N
        pan_ed1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 40, 50));

        icon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon1MouseClicked(evt);
            }
        });
        pan_ed1.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 200, 30, 30));

        icon2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon2MouseClicked(evt);
            }
        });
        pan_ed1.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 200, -1, 30));

        icon3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon3MouseClicked(evt);
            }
        });
        pan_ed1.add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 280, 30, 30));

        icon4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon4MouseClicked(evt);
            }
        });
        pan_ed1.add(icon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 280, -1, 30));

        jPanel1.add(pan_ed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 650));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\princy\\Desktop\\Brighton\\pic2\\bg2.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1278, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         int yes_or_no = JOptionPane.showConfirmDialog(this,"Do You Want to Exit","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(yes_or_no == JOptionPane.YES_OPTION){
        System.exit(0); 
        }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuserActionPerformed

    private void tpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpasswordActionPerformed

    private void tmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmobileActionPerformed

    private void tconpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tconpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tconpasswordActionPerformed

    private void tuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tuserFocusLost
       
       if (checkduplicateuser()==true){
          JOptionPane.showMessageDialog(this,"username is not available");
       }
      
    }//GEN-LAST:event_tuserFocusLost

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
       login login = new login();
                login.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(checkduplicateuser()==false){
            insertsignupdetails();
        }
        else{
        JOptionPane.showMessageDialog(this,"Please enter valid username");    
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseClicked
        icon2.setVisible(true);
        icon1.setVisible(false);
        tpassword.setEchoChar((char)0);
    }//GEN-LAST:event_icon1MouseClicked

    private void icon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MouseClicked
        icon1.setVisible(true);
       icon2.setVisible(false);
       tpassword.setEchoChar('*');
    }//GEN-LAST:event_icon2MouseClicked

    private void icon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon3MouseClicked
        icon4.setVisible(true);
        icon3.setVisible(false);
        tconpassword.setEchoChar((char)0);
    }//GEN-LAST:event_icon3MouseClicked

    private void icon4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon4MouseClicked
        icon3.setVisible(true);
       icon4.setVisible(false);
       tconpassword.setEchoChar('*');
    }//GEN-LAST:event_icon4MouseClicked

    private void tmobileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmobileMouseClicked
      
    }//GEN-LAST:event_tmobileMouseClicked

    private void tmobileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmobileMousePressed

    }//GEN-LAST:event_tmobileMousePressed

    private void tmobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tmobileKeyPressed
   String mobiles = tmobile.getText(); 
    int length = mobiles.length();
    
    char c = evt.getKeyChar();
    
    if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
    if(length < 12){
    tmobile.setEditable(true);
    }
    else{
      tmobile.setEditable(false);
    }
    }
    else{
     if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE  ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
     tmobile.setEditable(true);
     }
     else{
      tmobile.setEditable(false);
    }
    }
    }//GEN-LAST:event_tmobileKeyPressed

    private void tpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpasswordMouseClicked
       
    }//GEN-LAST:event_tpasswordMouseClicked

  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JPanel pan_ed1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private javax.swing.JPasswordField tconpassword;
    private app.bolivia.swing.JCTextField temail;
    private app.bolivia.swing.JCTextField tmobile;
    private javax.swing.JPasswordField tpassword;
    private app.bolivia.swing.JCTextField tuser;
    // End of variables declaration//GEN-END:variables

  
}
